FROM almalinux:10

# The FROM instruction defines the base image your Docker image will be built on top of.
# Think of it as saying:
# "Start with this image as the foundation of my container."
# FROM ubuntu:20.04        # Starts from a basic Ubuntu OS
# FROM node:18             # Starts with Node.js v18 installed
# FROM nginx               # Starts with the NGINX web server
# FROM alpine              # A lightweight Linux distro (great for small images)

# FROM is usually the first line in a Dockerfile