FROM  almalinux:9
EXPOSE 80/tcp

#EXPOSE tells Docker which port(s) your container's application will listen on at runtime.
#EXPOSE does NOT publish the port to your host

#You still need to map ports using -p when running the container:

#     FROM node:18

# WORKDIR /app
# COPY . .
# RUN npm install

# EXPOSE 3000

# CMD ["npm", "start"]