FROM almalinux:9
CMD  [ "google.com"]
ENTRYPOINT [ "ping", "-c5" ]







# docker run  entrypoint:1.0 ping -c5 youtube.com -->it will override the CMD instruction and it will ping the youtube.com

#you can override the entrypoint over runtime 
