FROM almalinux:9
ADD  https://raw.githubusercontent.com/prashanthbavikadi/basic-jenkin/refs/heads/main/01-ping.yaml /tmp/01-ping.yaml
ADD  sample-1.tar /tmp
CMD  ["sleep", "60"] 
 
# docker build -t <image>:<tag> .  --
# docker run -d <image>:<tag> ---
# docker exec -it <CONT ID> bash ---